project:
  type: website
website:
  title: "Introduction to nextflow"
  navbar:
    background: primary
  sidebar:
    search: true
    style: docked
    contents:
      - href: 1_intro.qmd
        text: Introduction
      - href: 2_channels.qmd
        text: Channels
      - href: 3_process.qmd
        text: Process
      - href: 4_nf-core.qmd
        text: nf-core
  page-navigation: true
  page-footer:
    left: |
      [![](logo_transparent_background.jpeg){fig-alt="Kuzman Consulting" width=220px}](https://www.kuzmanconsulting.com)
    right: |
      ![](ngschool-logo.svg){fig-alt="NGSchool" width=150px}
    background: light
lightbox: true
format:
  html:
    code-copy: true  # Enables the "Copy" button on all code blocks
    code-overflow: wrap  # Prevents horizontal scrolling
    toc: true
    toc-title: "Table of contents"
    code-fold: true
    theme: flatly
    embed-resources: true
    css: styles.css  # Link the custom CSS file
#    include-after-body: nextflow-highlighting.js
output: 
  html: default
